# Generated by Django 3.0.5 on 2020-04-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('cals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exp_date', models.DateTimeField()),
                ('cals', models.IntegerField(default=0)),
                ('glist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteapp.GList')),
            ],
        ),
        migrations.AddField(
            model_name='glist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteapp.User'),
        ),
    ]
